version: "3"

services:
    api:
        container_name: instant-ussd-api
        image: instant-ussd
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            -   "8000:8000"
        volumes:
            -   .:/var/www/html
